os: osx
osx_image: xcode11.3
language: swift

branches:
  only:
    - master

stages:
  - name: lint
    if: branch = master

jobs:
  include:
      - stage: lint
        install: gem install cocoapods -v '~> 1.7.5'
        script: pod lib lint
      - stage: test
        script:
        - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TwoWayBondageDemo.xcworkspace -scheme TwoWayBondageDemo -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
        - pod lib lint
